Repository fga-eps-mds/2020-1-Ziguen, pull requests merged in 2020-10, with the labels that each got.

#72 WIP: Networks
  .dockerignore
  Dockerfile
  docker-compose.yml
Labels: Devops, Docker/Docker-Compose, Networks, back-end, pull_request

#97 Pipeline-Ci
  .travis.yml
  README.md
  __tests__/integration/session.test.js
  package.json
  src/app.js
  yarn-error.log
  yarn.lock
Labels: Devops, Pipeline-CI, Test, Travis-Ci

#95 fix(#84): request bug resolved
  package.json
  src/app.js
  yarn-error.log
  yarn.lock
Labels: Node.js, back-end, bug, front-end

#99 Issue_templates
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issue-de-reportar-bug.md
  .github/ISSUE_TEMPLATE/issue-de-tarefas.md
  .github/ISSUE_TEMPLATE/issue-para-uma-nova-funcionalidade.md
  .github/issue_template/bug_report.md
  .github/issue_template/custom.md
  .github/issue_template/feature_request.md
  README.md
  docs/imagens/quadro_conhecimento_s5.jpg
  docs/imagens/quadro_conhecimento_s6.jpg
  docs/sprints/planning/sprint7.md
  docs/sprints/review/sprint6.md
Labels: Templates

#107 fix(106): resolving travel id bug
  src/app/controllers/TravelController.js
  src/app/controllers/TravelerController.js
  src/app/controllers/UserController.js
  src/app/models/Traveler.js
  src/app/models/User.js
  src/database/migrations/20200919213512-create-users.js
  src/database/migrations/20200922230551-travelers.js
  src/database/migrations/20200926012831-create-boats.js
  src/database/migrations/20200926020612-create-travels.js
  src/routes.js
Labels: Node.js, back-end, bug

#111 adding method
  src/app/controllers/BoatController.js
  src/app/controllers/TravelController.js
  src/routes.js
Labels: back-end

#110 fix(#108): adding descript method
  __tests__/database.sqlite
  src/app/controllers/UserController.js
  src/routes.js
Labels: Node.js, back-end, bug

#119 Restruturação do backlog
  docs/templates/sprints/planning/sprint0.md
  docs/templates/sprints/planning/sprint1.md
  docs/templates/sprints/planning/sprint2.md
  docs/templates/sprints/planning/sprint3.md
  docs/templates/sprints/planning/sprint4.md
  docs/templates/sprints/planning/sprint5.md
  docs/templates/sprints/planning/sprint6.md
  docs/templates/sprints/planning/sprint7.md
  docs/templates/sprints/planning/sprint8.md
  docs/templates/sprints/planning/sprint9.md
  docs/templates/sprints/review/sprint0.md
  docs/templates/sprints/review/sprint01.md
  docs/templates/sprints/review/sprint2.md
  docs/templates/sprints/review/sprint3.md
  docs/templates/sprints/review/sprint4.md
  docs/templates/sprints/review/sprint5.md
  docs/templates/sprints/review/sprint6.md
  docs/templates/sprints/review/sprint7.md
  docs/templates/sprints/review/sprint8.md
  docs/wiki/Backlog-do-Produto.md
Labels: documentation

#120 Boat capacity created
  src/app/controllers/BoatController.js
  src/app/models/Boat.js
  src/database/migrations/20200926012831-create-boats.js
Labels: back-end, feature, issue, pull_request, work in progress

#123 Code climate
  README.md
  codeclimate.yml
Labels: back-end, feature, pull_request

#126 fix(#121): rename travel to trip
  src/app/controllers/AdminController.js
  src/app/controllers/TravelController.js
  src/app/controllers/TripController.js
  src/app/models/Trip.js
  src/database/index.js
  src/database/migrations/20200926020612-create-travels.js
  src/routes.js
Labels: feature, pull_request, settings, work in progress

#127 fix(#121): resolving bug in test generated by renaming user to admini…
  __tests__/factores.js
  __tests__/integration/admin.test.js
  __tests__/integration/user.test.js
Labels: Test, back-end, bug
